### ISSUE TITLE
Two more ways of solving the problem

### ISSUE THREAD

**Issue by shageman** [msaspence/cobragems#1]
Hi Matthew,

Thanks for putting this together!

First off, I think a lot more people should weigh in on this, like @agenteo, @bleonard, @jetaggart, and all those I just forgot.

I agree with you that the managing of dependencies with a CBRA is pretty tedious and deserves a better solution. I think your suggestion is a valid approach and may be a nice solution for many projects out there.

I would like to propose two alternative ways of tackling the dependency problem:
### Aggregate Gemfiles and Gemspecs

With [maven](https://maven.apache.org) the java world knows about [project aggregation](https://maven.apache.org/guides/introduction/introduction-to-the-pom.html#Project_Aggregation). That effectively allows developers to maintain an application as a set of hierarchically structured projects. At my work, when we build java apps, that's how we do component-based Java. "pom" files are used to specify dependencies. "pom" files can reference "pom" files and inherit all their specifications.

I am quite certain that something like this would mean a huge change to the way bundler and rubygems work. It is very likely not something that we could push into those projects very easily (read "at all") since we would be breaking a lot of stuff.
### Gemfile, Gemspec generator

The one thing I don't like about your proposal is that it requires us to monkey patch Gemfile and Gemspec implementations. Instead of doing that, what if we build a system where you configure the contents of gemfile and gemspec in a separate file, say gem_config.yml (in each component). 

```

---
name: my_cbra_component
... #other gem config stuff
base_gem_config: ../../gem_config.yml #points to root app's gem config
dependencies:
  common:
    - rails
    - devise
    - cancancan
    - users
development dependencies:
  common:
    - rspec-rails
    - capybara
  versioned:
    - pry, 'x.x.x'
```

The idea is that any dependencies in dependencies -> common would get resolved through the config found in base_gem_config. The rest of the needed gem configuration (in a CBRA we don't need most of the Gemspec anyways...) would be in here as well.

Then there would be a generator script that ran through all the components in the CBRA which would generate valid `Gemfile` and `gemspec` files for every component and the main app.

The advantage of this approach is that it is invisible to bundler and rubygems. Of course, we would have to keep this up to date with changes in both of those projects to make sure we always generate valid definitions.
